Custom login
LVerhulst4321/PlanZ pull request #109
Opened 2022-10-29 16:31 UTC by LVerhulst4321

Add code to allow a custom login method.

PlanZ for Capricon is set up to allow people to login using their Capricon account that is set up by Capricon's registration. This means that code to connect to the reg system needs to be called.

I wanted to abstract this out a bit so that other groups could do something similar using their own system.

2022-10-30 08:33 UTC, lostcarpark commented
I've added a few comments. The only one that I think is actually a required change is the CommonHeader.php one. The others are suggestions, but I think they would improve it.

2022-10-30 16:24 UTC, LVerhulst4321 commented
Where did you add the comments? I don't see any comments.

2022-10-30 18:49 UTC, LVerhulst4321 commented
No, there's nothing there. No comments. Yes, I'm logged in. Strange.

2022-10-30 18:50 UTC, LVerhulst4321 commented on webpages/CommonCode.php
> +require_once('custom_functions.php');
Added a comment to test.

2022-10-30 18:50 UTC, LVerhulst4321 commented
I just added a test comment to the CommonCode.php file. Do you see it?

2022-10-30 19:00 UTC, lostcarpark commented
I can see your comment. I'm not sure why you can't see mine.

2022-10-30 19:05 UTC, LVerhulst4321 commented
Did you click on the "Add a single comment" button to save the comment?

2022-10-30 19:07 UTC, LVerhulst4321 commented
Also, do you see your comments on the Conversation page? Do you see mine on the Conversation page?

2022-10-30 19:12 UTC, lostcarpark commented
I can see my comments when logged in, but not when I sign out. But I can still see your comment when signed out. Will see if there's something with my permissions.

2022-10-30 19:28 UTC, lostcarpark commented
And yes I can see my comments on the conversation page. It's all rather baffling.

2022-10-30 19:33 UTC, lostcarpark requested changes
Figured out my comments were "pending" and I needed to "Submit Review".

2022-10-30 19:37 UTC, LVerhulst4321 commented
I see them now! Yay!

2022-10-31 01:59 UTC, LVerhulst4321 commented on webpages/config/db_name_sample.php
> +define("CUSTOM_LOGIN_PHP", ""); // Custom login function connected to reg system
Very good point! I'll move it.

2022-10-31 02:01 UTC, LVerhulst4321 commented on webpages/custom_functions.php
> +<?php
Good point. I was waffling between including or not.

2022-10-31 02:03 UTC, LVerhulst4321 commented on webpages/CommonCode.php
> +require_once('custom_functions.php');
Thanks for this update. I'll incorporate it.
The parenthesis are inherited from Zambia.

2022-10-31 02:04 UTC, LVerhulst4321 commented on webpages/CommonHeader.php
> +    $paramArray["LOGIN_PHP"] = defined('CUSTOM_LOGIN_PHP') ? CUSTOM_LOGIN_PHP : 'doLogin.php';
Good catch! Thanks!

2022-10-31 02:06 UTC, LVerhulst4321 commented on webpages/xsl/GlobalHeader.xsl
> +    <xsl:param name="LOGIN_PHP" select="'doLogin.php'" />
This code uses what the CommonHeader.php puts in the LOGIN_PHP parameter before it gets called and if there is nothing, then it defaults in the select value.

2022-10-31 07:39 UTC, lostcarpark commented on webpages/xsl/GlobalHeader.xsl
> +    <xsl:param name="LOGIN_PHP" select="'doLogin.php'" />
Yes, of course. Don't know why I didn't see that!

2022-10-31 07:42 UTC, lostcarpark commented on webpages/CommonCode.php
> +require_once('custom_functions.php');
There's no harm in having parenthesis, they just aren't required.

2022-10-31 07:44 UTC, lostcarpark approved these changes
All looks good to me now.

2022-11-01 04:19 UTC, merged